---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-doom
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1 
      maxUnavailable: 1
  selector:
    matchLabels:
      app: kubedoom-app
  template:
    metadata:
      labels:
        app: kubedoom-app
    spec:
      hostNetwork: true
      serviceAccountName: kubedoom
      containers:
      - image: storaxdev/kubedoom:0.5.0
        name: kubedoom
        ports:
        - name: http
          containerPort: 5900
          protocol: TCP
